<?php
include('includes/header.php');
include('includes/hero.php');
include('includes/stats.php');
include('includes/servicios.php');
include('includes/seguridad.php');
include('includes/soporte.php');
include('includes/infraestructura.php');
include('includes/footer.php');
